name: sa_application
description: Contains the main application package for GG Sch√ºler-App.

publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  animated_switcher_plus: ^1.1.1
  collection: ^1.19.1
  dartz: ^0.10.1
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  forui: ^0.10.0+1
  go_router: ^14.8.1
  intl: any
  loading_indicator: ^3.1.1
  locale_names: ^1.1.1
  mesh_gradient: ^1.3.8
  sa_common: 1.0.0
  sa_data: 1.0.0
  simple_shadow: ^0.3.1
  toastification: ^3.0.2
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: false
  generate: true
  assets:
    - assets/images/
  fonts:
    - family: MsMadi
      fonts:
        - asset: assets/fonts/MsMadi/MsMadi-Regular.ttf
